### ISSUE TITLE
We extracted the metadata. Where do we go from here?

### ISSUE THREAD

**Issue by JPcode05** [ArchiveTeam/youtube-items#17]
Now that YouTube would've privated all the videos, we were able to extract the metadata and the videos themselves.

What I would like to know is how are we going to publish the data we archived? They are going on the internet archive, but **how will the general public be able to view it?** And how long is this going to take?

Edit: I would also like to clarify what is in the metadata? Are comments included? I think they said yes, but I just want to make sure. (Edit 2: Comments _are_ included. All that @ivan said is comments are included and the data will be on IA.)

I've worked so hard on this project, I need a relief. I filled up 20GB of files on downloading these videos. And I would like to thank you guys for helping me on this project. Too bad we waited until near the end to get some work done.

**Comment by JustAnotherArchivist** [comment]
As with all our projects, all data goes into the Wayback Machine, though it may take quite some time until it shows up there (especially the actual videos, which *already* have a delay of a few months). I don't think comments will work because they use POST requests. The raw data (including comments) can be found [here](https://archive.org/details/archiveteam_youtube?and[]=mediatype%3A%22web%22), but be warned that it's not pleasant to work with these files.

**Comment by JPcode05** [comment]
> As with all our projects, all data goes into the Wayback Machine, though it may take quite some time until it shows up there (especially the actual videos, which _already_ have a delay of a few months). I don't think comments will work because they use POST requests. The raw data (including comments) can be found [here](https://archive.org/details/archiveteam_youtube?and%5B%5D=mediatype%3A%22web%22), but be warned that it's not pleasant to work with these files.

Is there eventually going to be a tool to read the metadata, maybe over the internet? It might take time for someone to make it, but I'll wait.

**Comment by JustAnotherArchivist** [comment]
Maybe, if someone writes one.

None of this is really related to this repository though. Further discussion can happen on IRC.
